version: "3.4"
services:
  committee-aerospike:
    image: aerospike/aerospike-server:5.7.0.12
    command: [ "--config-file", "/etc/aerospike.conf" ]
    ports:
      - "3000:3000"
    volumes:
      - ./aerospike.conf:/etc/aerospike.conf:ro
      - ./aerospike:/opt/aerospike/data/
    environment:
      - NAMESPACE=starkware
    ulimits:
      nofile:
        soft: 15000
        hard: 15000

  redis:
    image: redis
    command: redis-server --requirepass "redispassword"
    ports:
      - "6379:6379"

  committee:
    image: threesigmaxyz/starkexpress-operator-dac:${RELEASE_VERSION:-1.0.0}
    build:
      dockerfile: Dockerfile
      context: ./
      target: runtime
    volumes:
      - ./config.yml:/config.yml:ro
      - ./mtls:/mtls

    depends_on:
      - committee-aerospike

  committee-unit-tests:
    image: threesigmaxyz/starkexpress-operator-dac-unit-tests:${RELEASE_VERSION:-1.0.0}
    build:
      dockerfile: Dockerfile
      context: ./
      target: unit-tests
